python3 TestFilesGenerator.py Test_Activation float
python3 TestFilesGenerator.py Test_AttHead float
python3 TestFilesGenerator.py Test_Concat float
python3 TestFilesGenerator.py Test_Encoder float
python3 TestFilesGenerator.py Test_FeedForward float
python3 TestFilesGenerator.py Test_LayerNorm float
python3 TestFilesGenerator.py Test_Linear float
python3 TestFilesGenerator.py Test_Mask float
python3 TestFilesGenerator.py Test_MatAdd float
python3 TestFilesGenerator.py Test_MatMul float
python3 TestFilesGenerator.py Test_MultiHeadAtt float
python3 TestFilesGenerator.py Test_Scale float
python3 TestFilesGenerator.py Test_ScaleDotAtt float
python3 TestFilesGenerator.py Test_SoftMax float
python3 TestFilesGenerator.py Test_Transpose float
python3 TestFilesGenerator.py Test_VecAdd float
